import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Arrow from "../components/arrow";


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Antonio Beltran Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <main className={styles.main}>
        <div className={styles.leftSide}>
          <p>To My Projects</p>
          <Arrow href="projects" arrow="left" />
        </div>
        <div className={styles.mainDiv}>
          <div className={styles.hi}>
            
            {/* eslint-disable-next-line react/no-unescaped-entities */}
            <h1>Hi <br></br><br></br> I'm </h1>
          </div>
          <h1 className={styles.name}>Antonio Beltrán</h1>
          <div className={styles.imageContainer}>
            <Image src={"/programmer.gif"} height={200} width={250} alt="programmer"/>
          </div>
          <p>A Web Developer</p>
        </div>
        <div className={styles.rightSide}>
          <p>To About Me</p>
          <Arrow href="about" arrow="right" />
        </div>
        <div></div>
        <div>
          <p className={styles.instructions}>Please, select the page that you would like to visit on the header, or click on the arrows to know more about me.</p>
          <div className={styles.bottomSide}>
            <p>To Contact Me</p>
            <Arrow arrow="down" href="contact" />
          </div>
        </div>
        <div></div>
      </main>
    </div>
  );
}
