/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head';
import Image from 'next/image';
import Link from "next/link";
import styles from '../styles/Home.module.css';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Antonio Beltran Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <main className={styles.main}>
        
        <div></div>
        <div></div>
        <div></div>
        <div className={styles.arrowContainer}>
          <Link href="projects" passHref>
            <i className="fas fa-angle-double-left"></i>
          </Link>
        </div>
        <div className={styles.mainDiv}>
          <div >
            <h1 className={styles.hi}>Hi</h1>
            <h1>I'm </h1>
          </div>
          <h1 className={styles.name}>Antonio Beltrán</h1>
          <div className={styles.imageContainer}>
            <Image src={"/programmer.gif"} height={200} width={250} alt="programmer"/>
          </div>
          <p>A Web Developer</p>
        </div>
        <div className={styles.arrowContainer}>
          <Link href="about" passHref>
              <i className="fas fa-angle-double-right"></i>
          </Link>
        </div>
        <div></div>
        <div>
          <p className={styles.instructions}>Please, select the page that you would like to visit on the header, or click on the arrows to know more about me.</p>
          <div className={styles.arrowContainer}>
            <Link href="contact" passHref>
                <i className="fas fa-angle-double-down"></i>
            </Link>
          </div>
        </div>
        <div></div>
      </main>
      <footer className={styles.footer}>
        <p>Esto es el footer</p>
      </footer>
    </div>
  )
}
